# Generated by Django 3.1.4 on 2020-12-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201221_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, upload_to='UserProfile'),
        ),
    ]
