# Generated by Django 3.1.4 on 2020-12-21 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
