# Generated by Django 3.1.4 on 2020-12-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='header_image',
        ),
    ]
