# Generated by Django 3.1.4 on 2020-12-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20201222_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='header_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
